### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by Murat1Na** [cattodotpy/GeminiBot#1]
Hello i get this error when i startup the bot

Traceback (most recent call last):
  File "/home/container/main.py", line 16, in <module>
    config = json.load(file)
  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 15 column 1 (char 810)

**Comment by harrowfung** [comment]
Please check if your `config.json` is valid.

**Comment by Murat1Na** [comment]
> Please check if your `config.json` is valid.

yes my bad thanks, another thing..

Can you please make the bot work in reply too, not just mention if possible

**Comment by harrowfung** [comment]
> > Please check if your `config.json` is valid.
> 
> yes my bad thanks, another thing..
> 
> Can you please make the bot work in reply too, not just mention if possible

The first message must be a mention in order to receive a response from the bot, and after that, both replying and mentioning will work as well.

**Comment by Murat1Na** [comment]
> > > Please check if your `config.json` is valid.
> > 
> > 
> > yes my bad thanks, another thing..
> > Can you please make the bot work in reply too, not just mention if possible
> 
> The first message must be a mention in order to receive a response from the bot, and after that, both replying and mentioning will work as well.

Replying doesnt work to me at all, i tried and it doesnt work 

also for **delete command** i get this error: 
```Command raised an exception: UnboundLocalError: local variable 'message' referenced before assignment```
